/*
 * Copyright 2011-2021 Blender Foundation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License
 */
#ifdef _MSC_VER
#  if _MSC_VER < 1900
#    define snprintf _snprintf
#  endif
#  define popen _popen
#  define pclose _pclose
#if !defined(_CRT_SECURE_NO_WARNINGS)
#  define _CRT_SECURE_NO_WARNINGS
#endif
#endif

#include <contrib/hipew/include/hipew.h>
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>

#ifdef _WIN32
#  define WIN32_LEAN_AND_MEAN
#  define VC_EXTRALEAN
#  include <windows.h>

/* Utility macros. */

typedef HMODULE DynamicLibrary;

#  define dynamic_library_open(path)         LoadLibraryA(path)
#  define dynamic_library_close(lib)         FreeLibrary(lib)
#  define dynamic_library_find(lib, symbol)  GetProcAddress(lib, symbol)
#else
#  include <dlfcn.h>

typedef void* DynamicLibrary;

#  define dynamic_library_open(path)         dlopen(path, RTLD_NOW)
#  define dynamic_library_close(lib)         dlclose(lib)
#  define dynamic_library_find(lib, symbol)  dlsym(lib, symbol)
#endif

#define _LIBRARY_FIND_CHECKED(lib, name) \
        name = (t##name *)dynamic_library_find(lib, #name); \
        assert(name);

#define _LIBRARY_FIND(lib, name) \
        name = (t##name *)dynamic_library_find(lib, #name);


static DynamicLibrary hip_lib = NULL;
static DynamicLibrary hiprtc_lib = NULL;


#pragma region OROCHI_SUMMONER_REGION_hipew_cpp_1

/////
///// THIS REGION HAS BEEN AUTOMATICALLY GENERATED BY OROCHI SUMMONER.
///// Manual modification of this region is not recommended.
/////

t__hipPopCallConfiguration *__hipPopCallConfiguration;
t__hipPushCallConfiguration *__hipPushCallConfiguration;
thipApiName *hipApiName;
thipArray3DCreate *hipArray3DCreate;
thipArray3DGetDescriptor *hipArray3DGetDescriptor;
thipArrayCreate *hipArrayCreate;
thipArrayDestroy *hipArrayDestroy;
thipArrayGetDescriptor *hipArrayGetDescriptor;
thipArrayGetInfo *hipArrayGetInfo;
thipBindTexture *hipBindTexture;
thipBindTexture2D *hipBindTexture2D;
thipBindTextureToArray *hipBindTextureToArray;
thipBindTextureToMipmappedArray *hipBindTextureToMipmappedArray;
thipChooseDeviceR0600 *hipChooseDeviceR0600;
thipConfigureCall *hipConfigureCall;
thipCreateChannelDesc *hipCreateChannelDesc;
thipCreateSurfaceObject *hipCreateSurfaceObject;
thipCreateTextureObject *hipCreateTextureObject;
thipCtxCreate *hipCtxCreate;
thipCtxDestroy *hipCtxDestroy;
thipCtxDisablePeerAccess *hipCtxDisablePeerAccess;
thipCtxEnablePeerAccess *hipCtxEnablePeerAccess;
thipCtxGetApiVersion *hipCtxGetApiVersion;
thipCtxGetCacheConfig *hipCtxGetCacheConfig;
thipCtxGetCurrent *hipCtxGetCurrent;
thipCtxGetDevice *hipCtxGetDevice;
thipCtxGetFlags *hipCtxGetFlags;
thipCtxGetSharedMemConfig *hipCtxGetSharedMemConfig;
thipCtxPopCurrent *hipCtxPopCurrent;
thipCtxPushCurrent *hipCtxPushCurrent;
thipCtxSetCacheConfig *hipCtxSetCacheConfig;
thipCtxSetCurrent *hipCtxSetCurrent;
thipCtxSetSharedMemConfig *hipCtxSetSharedMemConfig;
thipCtxSynchronize *hipCtxSynchronize;
thipDestroyExternalMemory *hipDestroyExternalMemory;
thipDestroyExternalSemaphore *hipDestroyExternalSemaphore;
thipDestroySurfaceObject *hipDestroySurfaceObject;
thipDestroyTextureObject *hipDestroyTextureObject;
thipDeviceCanAccessPeer *hipDeviceCanAccessPeer;
thipDeviceComputeCapability *hipDeviceComputeCapability;
thipDeviceDisablePeerAccess *hipDeviceDisablePeerAccess;
thipDeviceEnablePeerAccess *hipDeviceEnablePeerAccess;
thipDeviceGet *hipDeviceGet;
thipDeviceGetAttribute *hipDeviceGetAttribute;
thipDeviceGetByPCIBusId *hipDeviceGetByPCIBusId;
thipDeviceGetCacheConfig *hipDeviceGetCacheConfig;
thipDeviceGetDefaultMemPool *hipDeviceGetDefaultMemPool;
thipDeviceGetGraphMemAttribute *hipDeviceGetGraphMemAttribute;
thipDeviceGetLimit *hipDeviceGetLimit;
thipDeviceGetMemPool *hipDeviceGetMemPool;
thipDeviceGetName *hipDeviceGetName;
thipDeviceGetP2PAttribute *hipDeviceGetP2PAttribute;
thipDeviceGetPCIBusId *hipDeviceGetPCIBusId;
thipDeviceGetSharedMemConfig *hipDeviceGetSharedMemConfig;
thipDeviceGetStreamPriorityRange *hipDeviceGetStreamPriorityRange;
thipDeviceGetUuid *hipDeviceGetUuid;
thipDeviceGraphMemTrim *hipDeviceGraphMemTrim;
thipDevicePrimaryCtxGetState *hipDevicePrimaryCtxGetState;
thipDevicePrimaryCtxRelease *hipDevicePrimaryCtxRelease;
thipDevicePrimaryCtxReset *hipDevicePrimaryCtxReset;
thipDevicePrimaryCtxRetain *hipDevicePrimaryCtxRetain;
thipDevicePrimaryCtxSetFlags *hipDevicePrimaryCtxSetFlags;
thipDeviceReset *hipDeviceReset;
thipDeviceSetCacheConfig *hipDeviceSetCacheConfig;
thipDeviceSetGraphMemAttribute *hipDeviceSetGraphMemAttribute;
thipDeviceSetLimit *hipDeviceSetLimit;
thipDeviceSetMemPool *hipDeviceSetMemPool;
thipDeviceSetSharedMemConfig *hipDeviceSetSharedMemConfig;
thipDeviceSynchronize *hipDeviceSynchronize;
thipDeviceTotalMem *hipDeviceTotalMem;
thipDriverGetVersion *hipDriverGetVersion;
thipDrvGetErrorName *hipDrvGetErrorName;
thipDrvGetErrorString *hipDrvGetErrorString;
thipDrvGraphAddMemcpyNode *hipDrvGraphAddMemcpyNode;
thipDrvMemcpy2DUnaligned *hipDrvMemcpy2DUnaligned;
thipDrvMemcpy3D *hipDrvMemcpy3D;
thipDrvMemcpy3DAsync *hipDrvMemcpy3DAsync;
thipDrvPointerGetAttributes *hipDrvPointerGetAttributes;
thipEventCreate *hipEventCreate;
thipEventCreateWithFlags *hipEventCreateWithFlags;
thipEventDestroy *hipEventDestroy;
thipEventElapsedTime *hipEventElapsedTime;
thipEventQuery *hipEventQuery;
thipEventRecord *hipEventRecord;
thipEventRecord_spt *hipEventRecord_spt;
thipEventSynchronize *hipEventSynchronize;
thipExtGetLastError *hipExtGetLastError;
thipExtGetLinkTypeAndHopCount *hipExtGetLinkTypeAndHopCount;
thipExtLaunchKernel *hipExtLaunchKernel;
thipExtLaunchMultiKernelMultiDevice *hipExtLaunchMultiKernelMultiDevice;
thipExtMallocWithFlags *hipExtMallocWithFlags;
thipExtStreamCreateWithCUMask *hipExtStreamCreateWithCUMask;
thipExtStreamGetCUMask *hipExtStreamGetCUMask;
thipExternalMemoryGetMappedBuffer *hipExternalMemoryGetMappedBuffer;
thipExternalMemoryGetMappedMipmappedArray *hipExternalMemoryGetMappedMipmappedArray;
thipFree *hipFree;
thipFreeArray *hipFreeArray;
thipFreeAsync *hipFreeAsync;
thipFreeHost *hipFreeHost;
thipFreeMipmappedArray *hipFreeMipmappedArray;
thipFuncGetAttribute *hipFuncGetAttribute;
thipFuncGetAttributes *hipFuncGetAttributes;
thipFuncSetAttribute *hipFuncSetAttribute;
thipFuncSetCacheConfig *hipFuncSetCacheConfig;
thipFuncSetSharedMemConfig *hipFuncSetSharedMemConfig;
thipGetChannelDesc *hipGetChannelDesc;
thipGetDevice *hipGetDevice;
thipGetDeviceCount *hipGetDeviceCount;
thipGetDeviceFlags *hipGetDeviceFlags;
thipGetDevicePropertiesR0600 *hipGetDevicePropertiesR0600;
thipGetErrorName *hipGetErrorName;
thipGetErrorString *hipGetErrorString;
thipGetLastError *hipGetLastError;
thipGetMipmappedArrayLevel *hipGetMipmappedArrayLevel;
thipGetStreamDeviceId *hipGetStreamDeviceId;
thipGetSymbolAddress *hipGetSymbolAddress;
thipGetSymbolSize *hipGetSymbolSize;
thipGetTextureAlignmentOffset *hipGetTextureAlignmentOffset;
thipGetTextureObjectResourceDesc *hipGetTextureObjectResourceDesc;
thipGetTextureObjectResourceViewDesc *hipGetTextureObjectResourceViewDesc;
thipGetTextureObjectTextureDesc *hipGetTextureObjectTextureDesc;
thipGetTextureReference *hipGetTextureReference;
thipGraphAddChildGraphNode *hipGraphAddChildGraphNode;
thipGraphAddDependencies *hipGraphAddDependencies;
thipGraphAddEmptyNode *hipGraphAddEmptyNode;
thipGraphAddEventRecordNode *hipGraphAddEventRecordNode;
thipGraphAddEventWaitNode *hipGraphAddEventWaitNode;
thipGraphAddHostNode *hipGraphAddHostNode;
thipGraphAddKernelNode *hipGraphAddKernelNode;
thipGraphAddMemAllocNode *hipGraphAddMemAllocNode;
thipGraphAddMemFreeNode *hipGraphAddMemFreeNode;
thipGraphAddMemcpyNode *hipGraphAddMemcpyNode;
thipGraphAddMemcpyNode1D *hipGraphAddMemcpyNode1D;
thipGraphAddMemcpyNodeFromSymbol *hipGraphAddMemcpyNodeFromSymbol;
thipGraphAddMemcpyNodeToSymbol *hipGraphAddMemcpyNodeToSymbol;
thipGraphAddMemsetNode *hipGraphAddMemsetNode;
thipGraphChildGraphNodeGetGraph *hipGraphChildGraphNodeGetGraph;
thipGraphClone *hipGraphClone;
thipGraphCreate *hipGraphCreate;
thipGraphDebugDotPrint *hipGraphDebugDotPrint;
thipGraphDestroy *hipGraphDestroy;
thipGraphDestroyNode *hipGraphDestroyNode;
thipGraphEventRecordNodeGetEvent *hipGraphEventRecordNodeGetEvent;
thipGraphEventRecordNodeSetEvent *hipGraphEventRecordNodeSetEvent;
thipGraphEventWaitNodeGetEvent *hipGraphEventWaitNodeGetEvent;
thipGraphEventWaitNodeSetEvent *hipGraphEventWaitNodeSetEvent;
thipGraphExecChildGraphNodeSetParams *hipGraphExecChildGraphNodeSetParams;
thipGraphExecDestroy *hipGraphExecDestroy;
thipGraphExecEventRecordNodeSetEvent *hipGraphExecEventRecordNodeSetEvent;
thipGraphExecEventWaitNodeSetEvent *hipGraphExecEventWaitNodeSetEvent;
thipGraphExecHostNodeSetParams *hipGraphExecHostNodeSetParams;
thipGraphExecKernelNodeSetParams *hipGraphExecKernelNodeSetParams;
thipGraphExecMemcpyNodeSetParams *hipGraphExecMemcpyNodeSetParams;
thipGraphExecMemcpyNodeSetParams1D *hipGraphExecMemcpyNodeSetParams1D;
thipGraphExecMemcpyNodeSetParamsFromSymbol *hipGraphExecMemcpyNodeSetParamsFromSymbol;
thipGraphExecMemcpyNodeSetParamsToSymbol *hipGraphExecMemcpyNodeSetParamsToSymbol;
thipGraphExecMemsetNodeSetParams *hipGraphExecMemsetNodeSetParams;
thipGraphExecUpdate *hipGraphExecUpdate;
thipGraphGetEdges *hipGraphGetEdges;
thipGraphGetNodes *hipGraphGetNodes;
thipGraphGetRootNodes *hipGraphGetRootNodes;
thipGraphHostNodeGetParams *hipGraphHostNodeGetParams;
thipGraphHostNodeSetParams *hipGraphHostNodeSetParams;
thipGraphInstantiate *hipGraphInstantiate;
thipGraphInstantiateWithFlags *hipGraphInstantiateWithFlags;
thipGraphKernelNodeCopyAttributes *hipGraphKernelNodeCopyAttributes;
thipGraphKernelNodeGetAttribute *hipGraphKernelNodeGetAttribute;
thipGraphKernelNodeGetParams *hipGraphKernelNodeGetParams;
thipGraphKernelNodeSetAttribute *hipGraphKernelNodeSetAttribute;
thipGraphKernelNodeSetParams *hipGraphKernelNodeSetParams;
thipGraphLaunch *hipGraphLaunch;
thipGraphLaunch_spt *hipGraphLaunch_spt;
thipGraphMemAllocNodeGetParams *hipGraphMemAllocNodeGetParams;
thipGraphMemFreeNodeGetParams *hipGraphMemFreeNodeGetParams;
thipGraphMemcpyNodeGetParams *hipGraphMemcpyNodeGetParams;
thipGraphMemcpyNodeSetParams *hipGraphMemcpyNodeSetParams;
thipGraphMemcpyNodeSetParams1D *hipGraphMemcpyNodeSetParams1D;
thipGraphMemcpyNodeSetParamsFromSymbol *hipGraphMemcpyNodeSetParamsFromSymbol;
thipGraphMemcpyNodeSetParamsToSymbol *hipGraphMemcpyNodeSetParamsToSymbol;
thipGraphMemsetNodeGetParams *hipGraphMemsetNodeGetParams;
thipGraphMemsetNodeSetParams *hipGraphMemsetNodeSetParams;
thipGraphNodeFindInClone *hipGraphNodeFindInClone;
thipGraphNodeGetDependencies *hipGraphNodeGetDependencies;
thipGraphNodeGetDependentNodes *hipGraphNodeGetDependentNodes;
thipGraphNodeGetEnabled *hipGraphNodeGetEnabled;
thipGraphNodeGetType *hipGraphNodeGetType;
thipGraphNodeSetEnabled *hipGraphNodeSetEnabled;
thipGraphReleaseUserObject *hipGraphReleaseUserObject;
thipGraphRemoveDependencies *hipGraphRemoveDependencies;
thipGraphRetainUserObject *hipGraphRetainUserObject;
thipGraphUpload *hipGraphUpload;
thipGraphicsMapResources *hipGraphicsMapResources;
thipGraphicsResourceGetMappedPointer *hipGraphicsResourceGetMappedPointer;
thipGraphicsSubResourceGetMappedArray *hipGraphicsSubResourceGetMappedArray;
thipGraphicsUnmapResources *hipGraphicsUnmapResources;
thipGraphicsUnregisterResource *hipGraphicsUnregisterResource;
thipHostAlloc *hipHostAlloc;
thipHostFree *hipHostFree;
thipHostGetDevicePointer *hipHostGetDevicePointer;
thipHostGetFlags *hipHostGetFlags;
thipHostMalloc *hipHostMalloc;
thipHostRegister *hipHostRegister;
thipHostUnregister *hipHostUnregister;
thipImportExternalMemory *hipImportExternalMemory;
thipImportExternalSemaphore *hipImportExternalSemaphore;
thipInit *hipInit;
thipIpcCloseMemHandle *hipIpcCloseMemHandle;
thipIpcGetEventHandle *hipIpcGetEventHandle;
thipIpcGetMemHandle *hipIpcGetMemHandle;
thipIpcOpenEventHandle *hipIpcOpenEventHandle;
thipIpcOpenMemHandle *hipIpcOpenMemHandle;
thipKernelNameRef *hipKernelNameRef;
thipKernelNameRefByPtr *hipKernelNameRefByPtr;
thipLaunchByPtr *hipLaunchByPtr;
thipLaunchCooperativeKernel *hipLaunchCooperativeKernel;
thipLaunchCooperativeKernelMultiDevice *hipLaunchCooperativeKernelMultiDevice;
thipLaunchCooperativeKernel_spt *hipLaunchCooperativeKernel_spt;
thipLaunchHostFunc *hipLaunchHostFunc;
thipLaunchHostFunc_spt *hipLaunchHostFunc_spt;
thipLaunchKernel *hipLaunchKernel;
thipLaunchKernel_spt *hipLaunchKernel_spt;
thipMalloc *hipMalloc;
thipMalloc3D *hipMalloc3D;
thipMalloc3DArray *hipMalloc3DArray;
thipMallocArray *hipMallocArray;
thipMallocAsync *hipMallocAsync;
thipMallocFromPoolAsync *hipMallocFromPoolAsync;
thipMallocHost *hipMallocHost;
thipMallocManaged *hipMallocManaged;
thipMallocMipmappedArray *hipMallocMipmappedArray;
thipMallocPitch *hipMallocPitch;
thipMemAddressFree *hipMemAddressFree;
thipMemAddressReserve *hipMemAddressReserve;
thipMemAdvise *hipMemAdvise;
thipMemAllocHost *hipMemAllocHost;
thipMemAllocPitch *hipMemAllocPitch;
thipMemCreate *hipMemCreate;
thipMemExportToShareableHandle *hipMemExportToShareableHandle;
thipMemGetAccess *hipMemGetAccess;
thipMemGetAddressRange *hipMemGetAddressRange;
thipMemGetAllocationGranularity *hipMemGetAllocationGranularity;
thipMemGetAllocationPropertiesFromHandle *hipMemGetAllocationPropertiesFromHandle;
thipMemGetInfo *hipMemGetInfo;
thipMemImportFromShareableHandle *hipMemImportFromShareableHandle;
thipMemMap *hipMemMap;
thipMemMapArrayAsync *hipMemMapArrayAsync;
thipMemPoolCreate *hipMemPoolCreate;
thipMemPoolDestroy *hipMemPoolDestroy;
thipMemPoolExportPointer *hipMemPoolExportPointer;
thipMemPoolExportToShareableHandle *hipMemPoolExportToShareableHandle;
thipMemPoolGetAccess *hipMemPoolGetAccess;
thipMemPoolGetAttribute *hipMemPoolGetAttribute;
thipMemPoolImportFromShareableHandle *hipMemPoolImportFromShareableHandle;
thipMemPoolImportPointer *hipMemPoolImportPointer;
thipMemPoolSetAccess *hipMemPoolSetAccess;
thipMemPoolSetAttribute *hipMemPoolSetAttribute;
thipMemPoolTrimTo *hipMemPoolTrimTo;
thipMemPrefetchAsync *hipMemPrefetchAsync;
thipMemPtrGetInfo *hipMemPtrGetInfo;
thipMemRangeGetAttribute *hipMemRangeGetAttribute;
thipMemRangeGetAttributes *hipMemRangeGetAttributes;
thipMemRelease *hipMemRelease;
thipMemRetainAllocationHandle *hipMemRetainAllocationHandle;
thipMemSetAccess *hipMemSetAccess;
thipMemUnmap *hipMemUnmap;
thipMemcpy *hipMemcpy;
thipMemcpy2D *hipMemcpy2D;
thipMemcpy2DAsync *hipMemcpy2DAsync;
thipMemcpy2DAsync_spt *hipMemcpy2DAsync_spt;
thipMemcpy2DFromArray *hipMemcpy2DFromArray;
thipMemcpy2DFromArrayAsync *hipMemcpy2DFromArrayAsync;
thipMemcpy2DFromArrayAsync_spt *hipMemcpy2DFromArrayAsync_spt;
thipMemcpy2DFromArray_spt *hipMemcpy2DFromArray_spt;
thipMemcpy2DToArray *hipMemcpy2DToArray;
thipMemcpy2DToArrayAsync *hipMemcpy2DToArrayAsync;
thipMemcpy2DToArrayAsync_spt *hipMemcpy2DToArrayAsync_spt;
thipMemcpy2DToArray_spt *hipMemcpy2DToArray_spt;
thipMemcpy2D_spt *hipMemcpy2D_spt;
thipMemcpy3D *hipMemcpy3D;
thipMemcpy3DAsync *hipMemcpy3DAsync;
thipMemcpy3DAsync_spt *hipMemcpy3DAsync_spt;
thipMemcpy3D_spt *hipMemcpy3D_spt;
thipMemcpyAsync *hipMemcpyAsync;
thipMemcpyAsync_spt *hipMemcpyAsync_spt;
thipMemcpyAtoH *hipMemcpyAtoH;
thipMemcpyDtoD *hipMemcpyDtoD;
thipMemcpyDtoDAsync *hipMemcpyDtoDAsync;
thipMemcpyDtoH *hipMemcpyDtoH;
thipMemcpyDtoHAsync *hipMemcpyDtoHAsync;
thipMemcpyFromArray *hipMemcpyFromArray;
thipMemcpyFromArray_spt *hipMemcpyFromArray_spt;
thipMemcpyFromSymbol *hipMemcpyFromSymbol;
thipMemcpyFromSymbolAsync *hipMemcpyFromSymbolAsync;
thipMemcpyFromSymbolAsync_spt *hipMemcpyFromSymbolAsync_spt;
thipMemcpyFromSymbol_spt *hipMemcpyFromSymbol_spt;
thipMemcpyHtoA *hipMemcpyHtoA;
thipMemcpyHtoD *hipMemcpyHtoD;
thipMemcpyHtoDAsync *hipMemcpyHtoDAsync;
thipMemcpyParam2D *hipMemcpyParam2D;
thipMemcpyParam2DAsync *hipMemcpyParam2DAsync;
thipMemcpyPeer *hipMemcpyPeer;
thipMemcpyPeerAsync *hipMemcpyPeerAsync;
thipMemcpyToArray *hipMemcpyToArray;
thipMemcpyToSymbol *hipMemcpyToSymbol;
thipMemcpyToSymbolAsync *hipMemcpyToSymbolAsync;
thipMemcpyToSymbolAsync_spt *hipMemcpyToSymbolAsync_spt;
thipMemcpyToSymbol_spt *hipMemcpyToSymbol_spt;
thipMemcpyWithStream *hipMemcpyWithStream;
thipMemcpy_spt *hipMemcpy_spt;
thipMemset *hipMemset;
thipMemset2D *hipMemset2D;
thipMemset2DAsync *hipMemset2DAsync;
thipMemset2DAsync_spt *hipMemset2DAsync_spt;
thipMemset2D_spt *hipMemset2D_spt;
thipMemset3D *hipMemset3D;
thipMemset3DAsync *hipMemset3DAsync;
thipMemset3DAsync_spt *hipMemset3DAsync_spt;
thipMemset3D_spt *hipMemset3D_spt;
thipMemsetAsync *hipMemsetAsync;
thipMemsetAsync_spt *hipMemsetAsync_spt;
thipMemsetD16 *hipMemsetD16;
thipMemsetD16Async *hipMemsetD16Async;
thipMemsetD32 *hipMemsetD32;
thipMemsetD32Async *hipMemsetD32Async;
thipMemsetD8 *hipMemsetD8;
thipMemsetD8Async *hipMemsetD8Async;
thipMemset_spt *hipMemset_spt;
thipMipmappedArrayCreate *hipMipmappedArrayCreate;
thipMipmappedArrayDestroy *hipMipmappedArrayDestroy;
thipMipmappedArrayGetLevel *hipMipmappedArrayGetLevel;
thipModuleGetFunction *hipModuleGetFunction;
thipModuleGetGlobal *hipModuleGetGlobal;
thipModuleGetTexRef *hipModuleGetTexRef;
thipModuleLaunchCooperativeKernel *hipModuleLaunchCooperativeKernel;
thipModuleLaunchCooperativeKernelMultiDevice *hipModuleLaunchCooperativeKernelMultiDevice;
thipModuleLaunchKernel *hipModuleLaunchKernel;
thipModuleLoad *hipModuleLoad;
thipModuleLoadData *hipModuleLoadData;
thipModuleLoadDataEx *hipModuleLoadDataEx;
thipModuleOccupancyMaxActiveBlocksPerMultiprocessor *hipModuleOccupancyMaxActiveBlocksPerMultiprocessor;
thipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags *hipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags;
thipModuleOccupancyMaxPotentialBlockSize *hipModuleOccupancyMaxPotentialBlockSize;
thipModuleOccupancyMaxPotentialBlockSizeWithFlags *hipModuleOccupancyMaxPotentialBlockSizeWithFlags;
thipModuleUnload *hipModuleUnload;
thipOccupancyMaxActiveBlocksPerMultiprocessor *hipOccupancyMaxActiveBlocksPerMultiprocessor;
thipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags *hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags;
thipOccupancyMaxPotentialBlockSize *hipOccupancyMaxPotentialBlockSize;
thipPeekAtLastError *hipPeekAtLastError;
thipPointerGetAttribute *hipPointerGetAttribute;
thipPointerGetAttributes *hipPointerGetAttributes;
thipPointerSetAttribute *hipPointerSetAttribute;
thipProfilerStart *hipProfilerStart;
thipProfilerStop *hipProfilerStop;
thipRuntimeGetVersion *hipRuntimeGetVersion;
thipSetDevice *hipSetDevice;
thipSetDeviceFlags *hipSetDeviceFlags;
thipSetupArgument *hipSetupArgument;
thipSignalExternalSemaphoresAsync *hipSignalExternalSemaphoresAsync;
thipStreamAddCallback *hipStreamAddCallback;
thipStreamAddCallback_spt *hipStreamAddCallback_spt;
thipStreamAttachMemAsync *hipStreamAttachMemAsync;
thipStreamBeginCapture *hipStreamBeginCapture;
thipStreamBeginCapture_spt *hipStreamBeginCapture_spt;
thipStreamCreate *hipStreamCreate;
thipStreamCreateWithFlags *hipStreamCreateWithFlags;
thipStreamCreateWithPriority *hipStreamCreateWithPriority;
thipStreamDestroy *hipStreamDestroy;
thipStreamEndCapture *hipStreamEndCapture;
thipStreamEndCapture_spt *hipStreamEndCapture_spt;
thipStreamGetCaptureInfo *hipStreamGetCaptureInfo;
thipStreamGetCaptureInfo_spt *hipStreamGetCaptureInfo_spt;
thipStreamGetCaptureInfo_v2 *hipStreamGetCaptureInfo_v2;
thipStreamGetCaptureInfo_v2_spt *hipStreamGetCaptureInfo_v2_spt;
thipStreamGetDevice *hipStreamGetDevice;
thipStreamGetFlags *hipStreamGetFlags;
thipStreamGetFlags_spt *hipStreamGetFlags_spt;
thipStreamGetPriority *hipStreamGetPriority;
thipStreamGetPriority_spt *hipStreamGetPriority_spt;
thipStreamIsCapturing *hipStreamIsCapturing;
thipStreamIsCapturing_spt *hipStreamIsCapturing_spt;
thipStreamQuery *hipStreamQuery;
thipStreamQuery_spt *hipStreamQuery_spt;
thipStreamSynchronize *hipStreamSynchronize;
thipStreamSynchronize_spt *hipStreamSynchronize_spt;
thipStreamUpdateCaptureDependencies *hipStreamUpdateCaptureDependencies;
thipStreamWaitEvent *hipStreamWaitEvent;
thipStreamWaitEvent_spt *hipStreamWaitEvent_spt;
thipStreamWaitValue32 *hipStreamWaitValue32;
thipStreamWaitValue64 *hipStreamWaitValue64;
thipStreamWriteValue32 *hipStreamWriteValue32;
thipStreamWriteValue64 *hipStreamWriteValue64;
thipTexObjectCreate *hipTexObjectCreate;
thipTexObjectDestroy *hipTexObjectDestroy;
thipTexObjectGetResourceDesc *hipTexObjectGetResourceDesc;
thipTexObjectGetResourceViewDesc *hipTexObjectGetResourceViewDesc;
thipTexObjectGetTextureDesc *hipTexObjectGetTextureDesc;
thipTexRefGetAddress *hipTexRefGetAddress;
thipTexRefGetAddressMode *hipTexRefGetAddressMode;
thipTexRefGetFilterMode *hipTexRefGetFilterMode;
thipTexRefGetFlags *hipTexRefGetFlags;
thipTexRefGetFormat *hipTexRefGetFormat;
thipTexRefGetMaxAnisotropy *hipTexRefGetMaxAnisotropy;
thipTexRefGetMipMappedArray *hipTexRefGetMipMappedArray;
thipTexRefGetMipmapFilterMode *hipTexRefGetMipmapFilterMode;
thipTexRefGetMipmapLevelBias *hipTexRefGetMipmapLevelBias;
thipTexRefGetMipmapLevelClamp *hipTexRefGetMipmapLevelClamp;
thipTexRefSetAddress *hipTexRefSetAddress;
thipTexRefSetAddress2D *hipTexRefSetAddress2D;
thipTexRefSetAddressMode *hipTexRefSetAddressMode;
thipTexRefSetArray *hipTexRefSetArray;
thipTexRefSetBorderColor *hipTexRefSetBorderColor;
thipTexRefSetFilterMode *hipTexRefSetFilterMode;
thipTexRefSetFlags *hipTexRefSetFlags;
thipTexRefSetFormat *hipTexRefSetFormat;
thipTexRefSetMaxAnisotropy *hipTexRefSetMaxAnisotropy;
thipTexRefSetMipmapFilterMode *hipTexRefSetMipmapFilterMode;
thipTexRefSetMipmapLevelBias *hipTexRefSetMipmapLevelBias;
thipTexRefSetMipmapLevelClamp *hipTexRefSetMipmapLevelClamp;
thipTexRefSetMipmappedArray *hipTexRefSetMipmappedArray;
thipThreadExchangeStreamCaptureMode *hipThreadExchangeStreamCaptureMode;
thipUnbindTexture *hipUnbindTexture;
thipUserObjectCreate *hipUserObjectCreate;
thipUserObjectRelease *hipUserObjectRelease;
thipUserObjectRetain *hipUserObjectRetain;
thipWaitExternalSemaphoresAsync *hipWaitExternalSemaphoresAsync;
thiprtcAddNameExpression *hiprtcAddNameExpression;
thiprtcCompileProgram *hiprtcCompileProgram;
thiprtcCreateProgram *hiprtcCreateProgram;
thiprtcDestroyProgram *hiprtcDestroyProgram;
thiprtcGetBitcode *hiprtcGetBitcode;
thiprtcGetBitcodeSize *hiprtcGetBitcodeSize;
thiprtcGetCode *hiprtcGetCode;
thiprtcGetCodeSize *hiprtcGetCodeSize;
thiprtcGetErrorString *hiprtcGetErrorString;
thiprtcGetLoweredName *hiprtcGetLoweredName;
thiprtcGetProgramLog *hiprtcGetProgramLog;
thiprtcGetProgramLogSize *hiprtcGetProgramLogSize;
thiprtcLinkAddData *hiprtcLinkAddData;
thiprtcLinkAddFile *hiprtcLinkAddFile;
thiprtcLinkComplete *hiprtcLinkComplete;
thiprtcLinkCreate *hiprtcLinkCreate;
thiprtcLinkDestroy *hiprtcLinkDestroy;
thiprtcVersion *hiprtcVersion;
tmake_char1 *make_char1;
tmake_char2 *make_char2;
tmake_char3 *make_char3;
tmake_char4 *make_char4;
tmake_double1 *make_double1;
tmake_double2 *make_double2;
tmake_double3 *make_double3;
tmake_double4 *make_double4;
tmake_float1 *make_float1;
tmake_float2 *make_float2;
tmake_float3 *make_float3;
tmake_float4 *make_float4;
tmake_hipExtent *make_hipExtent;
tmake_hipPitchedPtr *make_hipPitchedPtr;
tmake_hipPos *make_hipPos;
tmake_int1 *make_int1;
tmake_int2 *make_int2;
tmake_int3 *make_int3;
tmake_int4 *make_int4;
tmake_long1 *make_long1;
tmake_long2 *make_long2;
tmake_long3 *make_long3;
tmake_long4 *make_long4;
tmake_longlong1 *make_longlong1;
tmake_longlong2 *make_longlong2;
tmake_longlong3 *make_longlong3;
tmake_longlong4 *make_longlong4;
tmake_short1 *make_short1;
tmake_short2 *make_short2;
tmake_short3 *make_short3;
tmake_short4 *make_short4;
tmake_uchar1 *make_uchar1;
tmake_uchar2 *make_uchar2;
tmake_uchar3 *make_uchar3;
tmake_uchar4 *make_uchar4;
tmake_uint1 *make_uint1;
tmake_uint2 *make_uint2;
tmake_uint3 *make_uint3;
tmake_uint4 *make_uint4;
tmake_ulong1 *make_ulong1;
tmake_ulong2 *make_ulong2;
tmake_ulong3 *make_ulong3;
tmake_ulong4 *make_ulong4;
tmake_ulonglong1 *make_ulonglong1;
tmake_ulonglong2 *make_ulonglong2;
tmake_ulonglong3 *make_ulonglong3;
tmake_ulonglong4 *make_ulonglong4;
tmake_ushort1 *make_ushort1;
tmake_ushort2 *make_ushort2;
tmake_ushort3 *make_ushort3;
tmake_ushort4 *make_ushort4;



///// END REGION: OROCHI_SUMMONER_REGION_hipew_cpp_1
///// (region automatically generated by Orochi Summoner)
#pragma endregion


static DynamicLibrary dynamic_library_open_find(const char **paths) {
  int i = 0;
  while (paths[i] != NULL) {
      DynamicLibrary lib = dynamic_library_open(paths[i]);
      if (lib != NULL) {
        return lib;
      }
      ++i;
  }
  return NULL;
}

/* Implementation function. */
static void hipewHipExit(void) {
  if (hip_lib != NULL) {
    /*  Ignore errors. */
    dynamic_library_close(hip_lib);
    hip_lib = NULL;
  }
}

#ifdef _WIN32
static int hipewHasOldDriver(const char *hip_path) {
  DWORD verHandle = 0;
  DWORD verSize = GetFileVersionInfoSizeA(hip_path, &verHandle);
  int old_driver = 0;
  if (verSize != 0) {
    LPSTR verData = (LPSTR)malloc(verSize);
    if (GetFileVersionInfoA(hip_path, verHandle, verSize, verData)) {
      LPBYTE lpBuffer = NULL;
      UINT size = 0;
      if (VerQueryValueA(verData, "\\", (VOID FAR * FAR *)&lpBuffer, &size)) {
        if (size) {
          VS_FIXEDFILEINFO *verInfo = (VS_FIXEDFILEINFO *)lpBuffer;
          /* Magic value from
           * https://docs.microsoft.com/en-us/windows/win32/api/verrsrc/ns-verrsrc-vs_fixedfileinfo */
          if (verInfo->dwSignature == 0xfeef04bd) {
            unsigned int fileVersionLS0 = (verInfo->dwFileVersionLS >> 16) & 0xffff;
            unsigned int fileversionLS1 = (verInfo->dwFileVersionLS >> 0) & 0xffff;
            /* Corresponds to versions older than AMD Radeon Pro 21.Q4. */
            old_driver = ((fileVersionLS0 < 3354) || (fileVersionLS0 == 3354 && fileversionLS1 < 13));
          }
        }
      }
    }
    free(verData);
  }
  return old_driver;
}
#endif

void hipewInit( int* resultDriver, int* resultRtc, uint32_t flags )
{
  /* Library paths. */
#ifdef _WIN32
  /* Expected in C:/Windows/System32 or similar, no path needed. */
  const char* hip_paths[] = {"amdhip64_6.dll", "amdhip64.dll", NULL};
  const char* hiprtc_paths[] = {
                                "hiprtc0605.dll",
                                "hiprtc0604.dll",
                                "hiprtc0603.dll",
                                "hiprtc0602.dll",
                                "hiprtc0601.dll",
                                "hiprtc0600.dll",
                                "hiprtc0507.dll",  
                                "hiprtc0506.dll", 
                                "hiprtc0505.dll", 
                                "hiprtc0504.dll",
                                "hiprtc0503.dll",
                                NULL};
#elif defined(__APPLE__)
  /* Default installation path. */
  const char *hip_paths[] = {"", NULL};
  const char* hiprtc_paths[] = { NULL };
#else
  const char *hip_paths[] = { "/opt/rocm/hip/lib/libamdhip64.so",
                              "/opt/rocm/lib/libamdhip64.so", NULL };
  const char* hiprtc_paths[] = { "/opt/rocm/hip/lib/libhiprtc.so",
                              "/opt/rocm/lib/libhiprtc.so", NULL };
#endif
  static int initialized = 0;
  static int s_resultDriver = 0;
  static int s_resultRtc = 0;

  if (initialized) {
	*resultDriver = s_resultDriver;
	*resultRtc = s_resultRtc;
    return;
  }

  initialized = 1;

  int error = atexit( hipewHipExit );
  if (error) {
    s_resultDriver = HIPEW_ERROR_ATEXIT_FAILED;
    s_resultRtc = HIPEW_NOT_INITIALIZED;
    *resultDriver = s_resultDriver;
    *resultRtc = s_resultRtc;
    return;
  }

#ifdef _WIN32
  /* Test for driver version. */
  if(hipewHasOldDriver(hip_paths[0])) {
    s_resultDriver = HIPEW_ERROR_OLD_DRIVER;
    s_resultRtc = HIPEW_NOT_INITIALIZED;
    *resultDriver = s_resultDriver;
    *resultRtc = s_resultRtc;
    return;
  }
#endif

  /* Load library. */
  hip_lib = dynamic_library_open_find(hip_paths);
  hiprtc_lib = dynamic_library_open_find(hiprtc_paths);

  if (hip_lib == NULL) {
    s_resultDriver = HIPEW_ERROR_ATEXIT_FAILED;
    s_resultRtc = HIPEW_NOT_INITIALIZED;
	*resultDriver = s_resultDriver;
	*resultRtc = s_resultRtc;
    return;
  }




#pragma region OROCHI_SUMMONER_REGION_hipew_cpp_2

/////
///// THIS REGION HAS BEEN AUTOMATICALLY GENERATED BY OROCHI SUMMONER.
///// Manual modification of this region is not recommended.
/////

_LIBRARY_FIND( hip_lib, __hipPopCallConfiguration );
_LIBRARY_FIND( hip_lib, __hipPushCallConfiguration );
_LIBRARY_FIND( hip_lib, hipApiName );
_LIBRARY_FIND( hip_lib, hipArray3DCreate );
_LIBRARY_FIND( hip_lib, hipArray3DGetDescriptor );
_LIBRARY_FIND( hip_lib, hipArrayCreate );
_LIBRARY_FIND( hip_lib, hipArrayDestroy );
_LIBRARY_FIND( hip_lib, hipArrayGetDescriptor );
_LIBRARY_FIND( hip_lib, hipArrayGetInfo );
_LIBRARY_FIND( hip_lib, hipBindTexture );
_LIBRARY_FIND( hip_lib, hipBindTexture2D );
_LIBRARY_FIND( hip_lib, hipBindTextureToArray );
_LIBRARY_FIND( hip_lib, hipBindTextureToMipmappedArray );
_LIBRARY_FIND( hip_lib, hipChooseDeviceR0600 );
_LIBRARY_FIND( hip_lib, hipConfigureCall );
_LIBRARY_FIND( hip_lib, hipCreateChannelDesc );
_LIBRARY_FIND( hip_lib, hipCreateSurfaceObject );
_LIBRARY_FIND( hip_lib, hipCreateTextureObject );
_LIBRARY_FIND( hip_lib, hipCtxCreate );
_LIBRARY_FIND( hip_lib, hipCtxDestroy );
_LIBRARY_FIND( hip_lib, hipCtxDisablePeerAccess );
_LIBRARY_FIND( hip_lib, hipCtxEnablePeerAccess );
_LIBRARY_FIND( hip_lib, hipCtxGetApiVersion );
_LIBRARY_FIND( hip_lib, hipCtxGetCacheConfig );
_LIBRARY_FIND( hip_lib, hipCtxGetCurrent );
_LIBRARY_FIND( hip_lib, hipCtxGetDevice );
_LIBRARY_FIND( hip_lib, hipCtxGetFlags );
_LIBRARY_FIND( hip_lib, hipCtxGetSharedMemConfig );
_LIBRARY_FIND( hip_lib, hipCtxPopCurrent );
_LIBRARY_FIND( hip_lib, hipCtxPushCurrent );
_LIBRARY_FIND( hip_lib, hipCtxSetCacheConfig );
_LIBRARY_FIND( hip_lib, hipCtxSetCurrent );
_LIBRARY_FIND( hip_lib, hipCtxSetSharedMemConfig );
_LIBRARY_FIND( hip_lib, hipCtxSynchronize );
_LIBRARY_FIND( hip_lib, hipDestroyExternalMemory );
_LIBRARY_FIND( hip_lib, hipDestroyExternalSemaphore );
_LIBRARY_FIND( hip_lib, hipDestroySurfaceObject );
_LIBRARY_FIND( hip_lib, hipDestroyTextureObject );
_LIBRARY_FIND( hip_lib, hipDeviceCanAccessPeer );
_LIBRARY_FIND( hip_lib, hipDeviceComputeCapability );
_LIBRARY_FIND( hip_lib, hipDeviceDisablePeerAccess );
_LIBRARY_FIND( hip_lib, hipDeviceEnablePeerAccess );
_LIBRARY_FIND( hip_lib, hipDeviceGet );
_LIBRARY_FIND( hip_lib, hipDeviceGetAttribute );
_LIBRARY_FIND( hip_lib, hipDeviceGetByPCIBusId );
_LIBRARY_FIND( hip_lib, hipDeviceGetCacheConfig );
_LIBRARY_FIND( hip_lib, hipDeviceGetDefaultMemPool );
_LIBRARY_FIND( hip_lib, hipDeviceGetGraphMemAttribute );
_LIBRARY_FIND( hip_lib, hipDeviceGetLimit );
_LIBRARY_FIND( hip_lib, hipDeviceGetMemPool );
_LIBRARY_FIND( hip_lib, hipDeviceGetName );
_LIBRARY_FIND( hip_lib, hipDeviceGetP2PAttribute );
_LIBRARY_FIND( hip_lib, hipDeviceGetPCIBusId );
_LIBRARY_FIND( hip_lib, hipDeviceGetSharedMemConfig );
_LIBRARY_FIND( hip_lib, hipDeviceGetStreamPriorityRange );
_LIBRARY_FIND( hip_lib, hipDeviceGetUuid );
_LIBRARY_FIND( hip_lib, hipDeviceGraphMemTrim );
_LIBRARY_FIND( hip_lib, hipDevicePrimaryCtxGetState );
_LIBRARY_FIND( hip_lib, hipDevicePrimaryCtxRelease );
_LIBRARY_FIND( hip_lib, hipDevicePrimaryCtxReset );
_LIBRARY_FIND( hip_lib, hipDevicePrimaryCtxRetain );
_LIBRARY_FIND( hip_lib, hipDevicePrimaryCtxSetFlags );
_LIBRARY_FIND( hip_lib, hipDeviceReset );
_LIBRARY_FIND( hip_lib, hipDeviceSetCacheConfig );
_LIBRARY_FIND( hip_lib, hipDeviceSetGraphMemAttribute );
_LIBRARY_FIND( hip_lib, hipDeviceSetLimit );
_LIBRARY_FIND( hip_lib, hipDeviceSetMemPool );
_LIBRARY_FIND( hip_lib, hipDeviceSetSharedMemConfig );
_LIBRARY_FIND( hip_lib, hipDeviceSynchronize );
_LIBRARY_FIND( hip_lib, hipDeviceTotalMem );
_LIBRARY_FIND( hip_lib, hipDriverGetVersion );
_LIBRARY_FIND( hip_lib, hipDrvGetErrorName );
_LIBRARY_FIND( hip_lib, hipDrvGetErrorString );
// DLL not found for: hipDrvGraphAddMemcpyNode
_LIBRARY_FIND( hip_lib, hipDrvMemcpy2DUnaligned );
_LIBRARY_FIND( hip_lib, hipDrvMemcpy3D );
_LIBRARY_FIND( hip_lib, hipDrvMemcpy3DAsync );
_LIBRARY_FIND( hip_lib, hipDrvPointerGetAttributes );
_LIBRARY_FIND( hip_lib, hipEventCreate );
_LIBRARY_FIND( hip_lib, hipEventCreateWithFlags );
_LIBRARY_FIND( hip_lib, hipEventDestroy );
_LIBRARY_FIND( hip_lib, hipEventElapsedTime );
_LIBRARY_FIND( hip_lib, hipEventQuery );
_LIBRARY_FIND( hip_lib, hipEventRecord );
_LIBRARY_FIND( hip_lib, hipEventRecord_spt );
_LIBRARY_FIND( hip_lib, hipEventSynchronize );
_LIBRARY_FIND( hip_lib, hipExtGetLastError );
_LIBRARY_FIND( hip_lib, hipExtGetLinkTypeAndHopCount );
_LIBRARY_FIND( hip_lib, hipExtLaunchKernel );
_LIBRARY_FIND( hip_lib, hipExtLaunchMultiKernelMultiDevice );
_LIBRARY_FIND( hip_lib, hipExtMallocWithFlags );
_LIBRARY_FIND( hip_lib, hipExtStreamCreateWithCUMask );
_LIBRARY_FIND( hip_lib, hipExtStreamGetCUMask );
_LIBRARY_FIND( hip_lib, hipExternalMemoryGetMappedBuffer );
_LIBRARY_FIND( hip_lib, hipExternalMemoryGetMappedMipmappedArray );
_LIBRARY_FIND( hip_lib, hipFree );
_LIBRARY_FIND( hip_lib, hipFreeArray );
_LIBRARY_FIND( hip_lib, hipFreeAsync );
_LIBRARY_FIND( hip_lib, hipFreeHost );
_LIBRARY_FIND( hip_lib, hipFreeMipmappedArray );
_LIBRARY_FIND( hip_lib, hipFuncGetAttribute );
_LIBRARY_FIND( hip_lib, hipFuncGetAttributes );
_LIBRARY_FIND( hip_lib, hipFuncSetAttribute );
_LIBRARY_FIND( hip_lib, hipFuncSetCacheConfig );
_LIBRARY_FIND( hip_lib, hipFuncSetSharedMemConfig );
_LIBRARY_FIND( hip_lib, hipGetChannelDesc );
_LIBRARY_FIND( hip_lib, hipGetDevice );
_LIBRARY_FIND( hip_lib, hipGetDeviceCount );
_LIBRARY_FIND( hip_lib, hipGetDeviceFlags );
_LIBRARY_FIND( hip_lib, hipGetDevicePropertiesR0600 );
_LIBRARY_FIND( hip_lib, hipGetErrorName );
_LIBRARY_FIND( hip_lib, hipGetErrorString );
_LIBRARY_FIND( hip_lib, hipGetLastError );
_LIBRARY_FIND( hip_lib, hipGetMipmappedArrayLevel );
_LIBRARY_FIND( hip_lib, hipGetStreamDeviceId );
_LIBRARY_FIND( hip_lib, hipGetSymbolAddress );
_LIBRARY_FIND( hip_lib, hipGetSymbolSize );
_LIBRARY_FIND( hip_lib, hipGetTextureAlignmentOffset );
_LIBRARY_FIND( hip_lib, hipGetTextureObjectResourceDesc );
_LIBRARY_FIND( hip_lib, hipGetTextureObjectResourceViewDesc );
_LIBRARY_FIND( hip_lib, hipGetTextureObjectTextureDesc );
_LIBRARY_FIND( hip_lib, hipGetTextureReference );
_LIBRARY_FIND( hip_lib, hipGraphAddChildGraphNode );
_LIBRARY_FIND( hip_lib, hipGraphAddDependencies );
_LIBRARY_FIND( hip_lib, hipGraphAddEmptyNode );
_LIBRARY_FIND( hip_lib, hipGraphAddEventRecordNode );
_LIBRARY_FIND( hip_lib, hipGraphAddEventWaitNode );
_LIBRARY_FIND( hip_lib, hipGraphAddHostNode );
_LIBRARY_FIND( hip_lib, hipGraphAddKernelNode );
_LIBRARY_FIND( hip_lib, hipGraphAddMemAllocNode );
_LIBRARY_FIND( hip_lib, hipGraphAddMemFreeNode );
_LIBRARY_FIND( hip_lib, hipGraphAddMemcpyNode );
_LIBRARY_FIND( hip_lib, hipGraphAddMemcpyNode1D );
_LIBRARY_FIND( hip_lib, hipGraphAddMemcpyNodeFromSymbol );
_LIBRARY_FIND( hip_lib, hipGraphAddMemcpyNodeToSymbol );
_LIBRARY_FIND( hip_lib, hipGraphAddMemsetNode );
_LIBRARY_FIND( hip_lib, hipGraphChildGraphNodeGetGraph );
_LIBRARY_FIND( hip_lib, hipGraphClone );
_LIBRARY_FIND( hip_lib, hipGraphCreate );
_LIBRARY_FIND( hip_lib, hipGraphDebugDotPrint );
_LIBRARY_FIND( hip_lib, hipGraphDestroy );
_LIBRARY_FIND( hip_lib, hipGraphDestroyNode );
_LIBRARY_FIND( hip_lib, hipGraphEventRecordNodeGetEvent );
_LIBRARY_FIND( hip_lib, hipGraphEventRecordNodeSetEvent );
_LIBRARY_FIND( hip_lib, hipGraphEventWaitNodeGetEvent );
_LIBRARY_FIND( hip_lib, hipGraphEventWaitNodeSetEvent );
_LIBRARY_FIND( hip_lib, hipGraphExecChildGraphNodeSetParams );
_LIBRARY_FIND( hip_lib, hipGraphExecDestroy );
_LIBRARY_FIND( hip_lib, hipGraphExecEventRecordNodeSetEvent );
_LIBRARY_FIND( hip_lib, hipGraphExecEventWaitNodeSetEvent );
_LIBRARY_FIND( hip_lib, hipGraphExecHostNodeSetParams );
_LIBRARY_FIND( hip_lib, hipGraphExecKernelNodeSetParams );
_LIBRARY_FIND( hip_lib, hipGraphExecMemcpyNodeSetParams );
_LIBRARY_FIND( hip_lib, hipGraphExecMemcpyNodeSetParams1D );
_LIBRARY_FIND( hip_lib, hipGraphExecMemcpyNodeSetParamsFromSymbol );
_LIBRARY_FIND( hip_lib, hipGraphExecMemcpyNodeSetParamsToSymbol );
_LIBRARY_FIND( hip_lib, hipGraphExecMemsetNodeSetParams );
_LIBRARY_FIND( hip_lib, hipGraphExecUpdate );
_LIBRARY_FIND( hip_lib, hipGraphGetEdges );
_LIBRARY_FIND( hip_lib, hipGraphGetNodes );
_LIBRARY_FIND( hip_lib, hipGraphGetRootNodes );
_LIBRARY_FIND( hip_lib, hipGraphHostNodeGetParams );
_LIBRARY_FIND( hip_lib, hipGraphHostNodeSetParams );
_LIBRARY_FIND( hip_lib, hipGraphInstantiate );
_LIBRARY_FIND( hip_lib, hipGraphInstantiateWithFlags );
_LIBRARY_FIND( hip_lib, hipGraphKernelNodeCopyAttributes );
_LIBRARY_FIND( hip_lib, hipGraphKernelNodeGetAttribute );
_LIBRARY_FIND( hip_lib, hipGraphKernelNodeGetParams );
_LIBRARY_FIND( hip_lib, hipGraphKernelNodeSetAttribute );
_LIBRARY_FIND( hip_lib, hipGraphKernelNodeSetParams );
_LIBRARY_FIND( hip_lib, hipGraphLaunch );
_LIBRARY_FIND( hip_lib, hipGraphLaunch_spt );
_LIBRARY_FIND( hip_lib, hipGraphMemAllocNodeGetParams );
_LIBRARY_FIND( hip_lib, hipGraphMemFreeNodeGetParams );
_LIBRARY_FIND( hip_lib, hipGraphMemcpyNodeGetParams );
_LIBRARY_FIND( hip_lib, hipGraphMemcpyNodeSetParams );
_LIBRARY_FIND( hip_lib, hipGraphMemcpyNodeSetParams1D );
_LIBRARY_FIND( hip_lib, hipGraphMemcpyNodeSetParamsFromSymbol );
_LIBRARY_FIND( hip_lib, hipGraphMemcpyNodeSetParamsToSymbol );
_LIBRARY_FIND( hip_lib, hipGraphMemsetNodeGetParams );
_LIBRARY_FIND( hip_lib, hipGraphMemsetNodeSetParams );
_LIBRARY_FIND( hip_lib, hipGraphNodeFindInClone );
_LIBRARY_FIND( hip_lib, hipGraphNodeGetDependencies );
_LIBRARY_FIND( hip_lib, hipGraphNodeGetDependentNodes );
_LIBRARY_FIND( hip_lib, hipGraphNodeGetEnabled );
_LIBRARY_FIND( hip_lib, hipGraphNodeGetType );
_LIBRARY_FIND( hip_lib, hipGraphNodeSetEnabled );
_LIBRARY_FIND( hip_lib, hipGraphReleaseUserObject );
_LIBRARY_FIND( hip_lib, hipGraphRemoveDependencies );
_LIBRARY_FIND( hip_lib, hipGraphRetainUserObject );
_LIBRARY_FIND( hip_lib, hipGraphUpload );
_LIBRARY_FIND( hip_lib, hipGraphicsMapResources );
_LIBRARY_FIND( hip_lib, hipGraphicsResourceGetMappedPointer );
_LIBRARY_FIND( hip_lib, hipGraphicsSubResourceGetMappedArray );
_LIBRARY_FIND( hip_lib, hipGraphicsUnmapResources );
_LIBRARY_FIND( hip_lib, hipGraphicsUnregisterResource );
_LIBRARY_FIND( hip_lib, hipHostAlloc );
_LIBRARY_FIND( hip_lib, hipHostFree );
_LIBRARY_FIND( hip_lib, hipHostGetDevicePointer );
_LIBRARY_FIND( hip_lib, hipHostGetFlags );
_LIBRARY_FIND( hip_lib, hipHostMalloc );
_LIBRARY_FIND( hip_lib, hipHostRegister );
_LIBRARY_FIND( hip_lib, hipHostUnregister );
_LIBRARY_FIND( hip_lib, hipImportExternalMemory );
_LIBRARY_FIND( hip_lib, hipImportExternalSemaphore );
_LIBRARY_FIND( hip_lib, hipInit );
_LIBRARY_FIND( hip_lib, hipIpcCloseMemHandle );
_LIBRARY_FIND( hip_lib, hipIpcGetEventHandle );
_LIBRARY_FIND( hip_lib, hipIpcGetMemHandle );
_LIBRARY_FIND( hip_lib, hipIpcOpenEventHandle );
_LIBRARY_FIND( hip_lib, hipIpcOpenMemHandle );
_LIBRARY_FIND( hip_lib, hipKernelNameRef );
// DLL not found for: hipKernelNameRefByPtr
_LIBRARY_FIND( hip_lib, hipLaunchByPtr );
_LIBRARY_FIND( hip_lib, hipLaunchCooperativeKernel );
_LIBRARY_FIND( hip_lib, hipLaunchCooperativeKernelMultiDevice );
_LIBRARY_FIND( hip_lib, hipLaunchCooperativeKernel_spt );
_LIBRARY_FIND( hip_lib, hipLaunchHostFunc );
_LIBRARY_FIND( hip_lib, hipLaunchHostFunc_spt );
_LIBRARY_FIND( hip_lib, hipLaunchKernel );
_LIBRARY_FIND( hip_lib, hipLaunchKernel_spt );
_LIBRARY_FIND( hip_lib, hipMalloc );
_LIBRARY_FIND( hip_lib, hipMalloc3D );
_LIBRARY_FIND( hip_lib, hipMalloc3DArray );
_LIBRARY_FIND( hip_lib, hipMallocArray );
_LIBRARY_FIND( hip_lib, hipMallocAsync );
_LIBRARY_FIND( hip_lib, hipMallocFromPoolAsync );
_LIBRARY_FIND( hip_lib, hipMallocHost );
_LIBRARY_FIND( hip_lib, hipMallocManaged );
_LIBRARY_FIND( hip_lib, hipMallocMipmappedArray );
_LIBRARY_FIND( hip_lib, hipMallocPitch );
_LIBRARY_FIND( hip_lib, hipMemAddressFree );
_LIBRARY_FIND( hip_lib, hipMemAddressReserve );
_LIBRARY_FIND( hip_lib, hipMemAdvise );
_LIBRARY_FIND( hip_lib, hipMemAllocHost );
_LIBRARY_FIND( hip_lib, hipMemAllocPitch );
_LIBRARY_FIND( hip_lib, hipMemCreate );
_LIBRARY_FIND( hip_lib, hipMemExportToShareableHandle );
_LIBRARY_FIND( hip_lib, hipMemGetAccess );
_LIBRARY_FIND( hip_lib, hipMemGetAddressRange );
_LIBRARY_FIND( hip_lib, hipMemGetAllocationGranularity );
_LIBRARY_FIND( hip_lib, hipMemGetAllocationPropertiesFromHandle );
_LIBRARY_FIND( hip_lib, hipMemGetInfo );
_LIBRARY_FIND( hip_lib, hipMemImportFromShareableHandle );
_LIBRARY_FIND( hip_lib, hipMemMap );
_LIBRARY_FIND( hip_lib, hipMemMapArrayAsync );
_LIBRARY_FIND( hip_lib, hipMemPoolCreate );
_LIBRARY_FIND( hip_lib, hipMemPoolDestroy );
_LIBRARY_FIND( hip_lib, hipMemPoolExportPointer );
_LIBRARY_FIND( hip_lib, hipMemPoolExportToShareableHandle );
_LIBRARY_FIND( hip_lib, hipMemPoolGetAccess );
_LIBRARY_FIND( hip_lib, hipMemPoolGetAttribute );
_LIBRARY_FIND( hip_lib, hipMemPoolImportFromShareableHandle );
_LIBRARY_FIND( hip_lib, hipMemPoolImportPointer );
_LIBRARY_FIND( hip_lib, hipMemPoolSetAccess );
_LIBRARY_FIND( hip_lib, hipMemPoolSetAttribute );
_LIBRARY_FIND( hip_lib, hipMemPoolTrimTo );
_LIBRARY_FIND( hip_lib, hipMemPrefetchAsync );
_LIBRARY_FIND( hip_lib, hipMemPtrGetInfo );
_LIBRARY_FIND( hip_lib, hipMemRangeGetAttribute );
_LIBRARY_FIND( hip_lib, hipMemRangeGetAttributes );
_LIBRARY_FIND( hip_lib, hipMemRelease );
_LIBRARY_FIND( hip_lib, hipMemRetainAllocationHandle );
_LIBRARY_FIND( hip_lib, hipMemSetAccess );
_LIBRARY_FIND( hip_lib, hipMemUnmap );
_LIBRARY_FIND( hip_lib, hipMemcpy );
_LIBRARY_FIND( hip_lib, hipMemcpy2D );
_LIBRARY_FIND( hip_lib, hipMemcpy2DAsync );
_LIBRARY_FIND( hip_lib, hipMemcpy2DAsync_spt );
_LIBRARY_FIND( hip_lib, hipMemcpy2DFromArray );
_LIBRARY_FIND( hip_lib, hipMemcpy2DFromArrayAsync );
_LIBRARY_FIND( hip_lib, hipMemcpy2DFromArrayAsync_spt );
_LIBRARY_FIND( hip_lib, hipMemcpy2DFromArray_spt );
_LIBRARY_FIND( hip_lib, hipMemcpy2DToArray );
_LIBRARY_FIND( hip_lib, hipMemcpy2DToArrayAsync );
_LIBRARY_FIND( hip_lib, hipMemcpy2DToArrayAsync_spt );
_LIBRARY_FIND( hip_lib, hipMemcpy2DToArray_spt );
_LIBRARY_FIND( hip_lib, hipMemcpy2D_spt );
_LIBRARY_FIND( hip_lib, hipMemcpy3D );
_LIBRARY_FIND( hip_lib, hipMemcpy3DAsync );
_LIBRARY_FIND( hip_lib, hipMemcpy3DAsync_spt );
_LIBRARY_FIND( hip_lib, hipMemcpy3D_spt );
_LIBRARY_FIND( hip_lib, hipMemcpyAsync );
_LIBRARY_FIND( hip_lib, hipMemcpyAsync_spt );
_LIBRARY_FIND( hip_lib, hipMemcpyAtoH );
_LIBRARY_FIND( hip_lib, hipMemcpyDtoD );
_LIBRARY_FIND( hip_lib, hipMemcpyDtoDAsync );
_LIBRARY_FIND( hip_lib, hipMemcpyDtoH );
_LIBRARY_FIND( hip_lib, hipMemcpyDtoHAsync );
_LIBRARY_FIND( hip_lib, hipMemcpyFromArray );
_LIBRARY_FIND( hip_lib, hipMemcpyFromArray_spt );
_LIBRARY_FIND( hip_lib, hipMemcpyFromSymbol );
_LIBRARY_FIND( hip_lib, hipMemcpyFromSymbolAsync );
_LIBRARY_FIND( hip_lib, hipMemcpyFromSymbolAsync_spt );
_LIBRARY_FIND( hip_lib, hipMemcpyFromSymbol_spt );
_LIBRARY_FIND( hip_lib, hipMemcpyHtoA );
_LIBRARY_FIND( hip_lib, hipMemcpyHtoD );
_LIBRARY_FIND( hip_lib, hipMemcpyHtoDAsync );
_LIBRARY_FIND( hip_lib, hipMemcpyParam2D );
_LIBRARY_FIND( hip_lib, hipMemcpyParam2DAsync );
_LIBRARY_FIND( hip_lib, hipMemcpyPeer );
_LIBRARY_FIND( hip_lib, hipMemcpyPeerAsync );
_LIBRARY_FIND( hip_lib, hipMemcpyToArray );
_LIBRARY_FIND( hip_lib, hipMemcpyToSymbol );
_LIBRARY_FIND( hip_lib, hipMemcpyToSymbolAsync );
_LIBRARY_FIND( hip_lib, hipMemcpyToSymbolAsync_spt );
_LIBRARY_FIND( hip_lib, hipMemcpyToSymbol_spt );
_LIBRARY_FIND( hip_lib, hipMemcpyWithStream );
_LIBRARY_FIND( hip_lib, hipMemcpy_spt );
_LIBRARY_FIND( hip_lib, hipMemset );
_LIBRARY_FIND( hip_lib, hipMemset2D );
_LIBRARY_FIND( hip_lib, hipMemset2DAsync );
_LIBRARY_FIND( hip_lib, hipMemset2DAsync_spt );
_LIBRARY_FIND( hip_lib, hipMemset2D_spt );
_LIBRARY_FIND( hip_lib, hipMemset3D );
_LIBRARY_FIND( hip_lib, hipMemset3DAsync );
_LIBRARY_FIND( hip_lib, hipMemset3DAsync_spt );
_LIBRARY_FIND( hip_lib, hipMemset3D_spt );
_LIBRARY_FIND( hip_lib, hipMemsetAsync );
_LIBRARY_FIND( hip_lib, hipMemsetAsync_spt );
_LIBRARY_FIND( hip_lib, hipMemsetD16 );
_LIBRARY_FIND( hip_lib, hipMemsetD16Async );
_LIBRARY_FIND( hip_lib, hipMemsetD32 );
_LIBRARY_FIND( hip_lib, hipMemsetD32Async );
_LIBRARY_FIND( hip_lib, hipMemsetD8 );
_LIBRARY_FIND( hip_lib, hipMemsetD8Async );
_LIBRARY_FIND( hip_lib, hipMemset_spt );
_LIBRARY_FIND( hip_lib, hipMipmappedArrayCreate );
_LIBRARY_FIND( hip_lib, hipMipmappedArrayDestroy );
_LIBRARY_FIND( hip_lib, hipMipmappedArrayGetLevel );
_LIBRARY_FIND( hip_lib, hipModuleGetFunction );
_LIBRARY_FIND( hip_lib, hipModuleGetGlobal );
_LIBRARY_FIND( hip_lib, hipModuleGetTexRef );
_LIBRARY_FIND( hip_lib, hipModuleLaunchCooperativeKernel );
_LIBRARY_FIND( hip_lib, hipModuleLaunchCooperativeKernelMultiDevice );
_LIBRARY_FIND( hip_lib, hipModuleLaunchKernel );
_LIBRARY_FIND( hip_lib, hipModuleLoad );
_LIBRARY_FIND( hip_lib, hipModuleLoadData );
_LIBRARY_FIND( hip_lib, hipModuleLoadDataEx );
_LIBRARY_FIND( hip_lib, hipModuleOccupancyMaxActiveBlocksPerMultiprocessor );
_LIBRARY_FIND( hip_lib, hipModuleOccupancyMaxActiveBlocksPerMultiprocessorWithFlags );
_LIBRARY_FIND( hip_lib, hipModuleOccupancyMaxPotentialBlockSize );
_LIBRARY_FIND( hip_lib, hipModuleOccupancyMaxPotentialBlockSizeWithFlags );
_LIBRARY_FIND( hip_lib, hipModuleUnload );
_LIBRARY_FIND( hip_lib, hipOccupancyMaxActiveBlocksPerMultiprocessor );
_LIBRARY_FIND( hip_lib, hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags );
_LIBRARY_FIND( hip_lib, hipOccupancyMaxPotentialBlockSize );
_LIBRARY_FIND( hip_lib, hipPeekAtLastError );
_LIBRARY_FIND( hip_lib, hipPointerGetAttribute );
_LIBRARY_FIND( hip_lib, hipPointerGetAttributes );
// DLL not found for: hipPointerSetAttribute
_LIBRARY_FIND( hip_lib, hipProfilerStart );
_LIBRARY_FIND( hip_lib, hipProfilerStop );
_LIBRARY_FIND( hip_lib, hipRuntimeGetVersion );
_LIBRARY_FIND( hip_lib, hipSetDevice );
_LIBRARY_FIND( hip_lib, hipSetDeviceFlags );
_LIBRARY_FIND( hip_lib, hipSetupArgument );
_LIBRARY_FIND( hip_lib, hipSignalExternalSemaphoresAsync );
_LIBRARY_FIND( hip_lib, hipStreamAddCallback );
_LIBRARY_FIND( hip_lib, hipStreamAddCallback_spt );
_LIBRARY_FIND( hip_lib, hipStreamAttachMemAsync );
_LIBRARY_FIND( hip_lib, hipStreamBeginCapture );
_LIBRARY_FIND( hip_lib, hipStreamBeginCapture_spt );
_LIBRARY_FIND( hip_lib, hipStreamCreate );
_LIBRARY_FIND( hip_lib, hipStreamCreateWithFlags );
_LIBRARY_FIND( hip_lib, hipStreamCreateWithPriority );
_LIBRARY_FIND( hip_lib, hipStreamDestroy );
_LIBRARY_FIND( hip_lib, hipStreamEndCapture );
_LIBRARY_FIND( hip_lib, hipStreamEndCapture_spt );
_LIBRARY_FIND( hip_lib, hipStreamGetCaptureInfo );
_LIBRARY_FIND( hip_lib, hipStreamGetCaptureInfo_spt );
_LIBRARY_FIND( hip_lib, hipStreamGetCaptureInfo_v2 );
_LIBRARY_FIND( hip_lib, hipStreamGetCaptureInfo_v2_spt );
_LIBRARY_FIND( hip_lib, hipStreamGetDevice );
_LIBRARY_FIND( hip_lib, hipStreamGetFlags );
_LIBRARY_FIND( hip_lib, hipStreamGetFlags_spt );
_LIBRARY_FIND( hip_lib, hipStreamGetPriority );
_LIBRARY_FIND( hip_lib, hipStreamGetPriority_spt );
_LIBRARY_FIND( hip_lib, hipStreamIsCapturing );
_LIBRARY_FIND( hip_lib, hipStreamIsCapturing_spt );
_LIBRARY_FIND( hip_lib, hipStreamQuery );
_LIBRARY_FIND( hip_lib, hipStreamQuery_spt );
_LIBRARY_FIND( hip_lib, hipStreamSynchronize );
_LIBRARY_FIND( hip_lib, hipStreamSynchronize_spt );
_LIBRARY_FIND( hip_lib, hipStreamUpdateCaptureDependencies );
_LIBRARY_FIND( hip_lib, hipStreamWaitEvent );
_LIBRARY_FIND( hip_lib, hipStreamWaitEvent_spt );
_LIBRARY_FIND( hip_lib, hipStreamWaitValue32 );
_LIBRARY_FIND( hip_lib, hipStreamWaitValue64 );
_LIBRARY_FIND( hip_lib, hipStreamWriteValue32 );
_LIBRARY_FIND( hip_lib, hipStreamWriteValue64 );
_LIBRARY_FIND( hip_lib, hipTexObjectCreate );
_LIBRARY_FIND( hip_lib, hipTexObjectDestroy );
_LIBRARY_FIND( hip_lib, hipTexObjectGetResourceDesc );
_LIBRARY_FIND( hip_lib, hipTexObjectGetResourceViewDesc );
_LIBRARY_FIND( hip_lib, hipTexObjectGetTextureDesc );
_LIBRARY_FIND( hip_lib, hipTexRefGetAddress );
_LIBRARY_FIND( hip_lib, hipTexRefGetAddressMode );
_LIBRARY_FIND( hip_lib, hipTexRefGetFilterMode );
_LIBRARY_FIND( hip_lib, hipTexRefGetFlags );
_LIBRARY_FIND( hip_lib, hipTexRefGetFormat );
_LIBRARY_FIND( hip_lib, hipTexRefGetMaxAnisotropy );
// DLL not found for: hipTexRefGetMipMappedArray
_LIBRARY_FIND( hip_lib, hipTexRefGetMipmapFilterMode );
_LIBRARY_FIND( hip_lib, hipTexRefGetMipmapLevelBias );
_LIBRARY_FIND( hip_lib, hipTexRefGetMipmapLevelClamp );
_LIBRARY_FIND( hip_lib, hipTexRefSetAddress );
_LIBRARY_FIND( hip_lib, hipTexRefSetAddress2D );
_LIBRARY_FIND( hip_lib, hipTexRefSetAddressMode );
_LIBRARY_FIND( hip_lib, hipTexRefSetArray );
_LIBRARY_FIND( hip_lib, hipTexRefSetBorderColor );
_LIBRARY_FIND( hip_lib, hipTexRefSetFilterMode );
_LIBRARY_FIND( hip_lib, hipTexRefSetFlags );
_LIBRARY_FIND( hip_lib, hipTexRefSetFormat );
_LIBRARY_FIND( hip_lib, hipTexRefSetMaxAnisotropy );
_LIBRARY_FIND( hip_lib, hipTexRefSetMipmapFilterMode );
_LIBRARY_FIND( hip_lib, hipTexRefSetMipmapLevelBias );
_LIBRARY_FIND( hip_lib, hipTexRefSetMipmapLevelClamp );
_LIBRARY_FIND( hip_lib, hipTexRefSetMipmappedArray );
_LIBRARY_FIND( hip_lib, hipThreadExchangeStreamCaptureMode );
_LIBRARY_FIND( hip_lib, hipUnbindTexture );
_LIBRARY_FIND( hip_lib, hipUserObjectCreate );
_LIBRARY_FIND( hip_lib, hipUserObjectRelease );
_LIBRARY_FIND( hip_lib, hipUserObjectRetain );
_LIBRARY_FIND( hip_lib, hipWaitExternalSemaphoresAsync );
// DLL not found for: make_char1
// DLL not found for: make_char2
// DLL not found for: make_char3
// DLL not found for: make_char4
// DLL not found for: make_double1
// DLL not found for: make_double2
// DLL not found for: make_double3
// DLL not found for: make_double4
// DLL not found for: make_float1
// DLL not found for: make_float2
// DLL not found for: make_float3
// DLL not found for: make_float4
// DLL not found for: make_hipExtent
// DLL not found for: make_hipPitchedPtr
// DLL not found for: make_hipPos
// DLL not found for: make_int1
// DLL not found for: make_int2
// DLL not found for: make_int3
// DLL not found for: make_int4
// DLL not found for: make_long1
// DLL not found for: make_long2
// DLL not found for: make_long3
// DLL not found for: make_long4
// DLL not found for: make_longlong1
// DLL not found for: make_longlong2
// DLL not found for: make_longlong3
// DLL not found for: make_longlong4
// DLL not found for: make_short1
// DLL not found for: make_short2
// DLL not found for: make_short3
// DLL not found for: make_short4
// DLL not found for: make_uchar1
// DLL not found for: make_uchar2
// DLL not found for: make_uchar3
// DLL not found for: make_uchar4
// DLL not found for: make_uint1
// DLL not found for: make_uint2
// DLL not found for: make_uint3
// DLL not found for: make_uint4
// DLL not found for: make_ulong1
// DLL not found for: make_ulong2
// DLL not found for: make_ulong3
// DLL not found for: make_ulong4
// DLL not found for: make_ulonglong1
// DLL not found for: make_ulonglong2
// DLL not found for: make_ulonglong3
// DLL not found for: make_ulonglong4
// DLL not found for: make_ushort1
// DLL not found for: make_ushort2
// DLL not found for: make_ushort3
// DLL not found for: make_ushort4


///// END REGION: OROCHI_SUMMONER_REGION_hipew_cpp_2
///// (region automatically generated by Orochi Summoner)
#pragma endregion



  s_resultDriver = HIPEW_SUCCESS;
  *resultDriver = s_resultDriver;

  if( ( flags & HIPEW_INIT_HIPRTC ) == 0 )
  {
	s_resultRtc = HIPEW_NOT_INITIALIZED;
	*resultRtc = s_resultRtc;
	return;
  }

  auto rtcLib = hiprtc_lib ? hiprtc_lib : hip_lib;
  _LIBRARY_FIND( rtcLib, hiprtcGetErrorString );
  if( hiprtcGetErrorString )
  {



#pragma region OROCHI_SUMMONER_REGION_hipew_cpp_rtc

/////
///// THIS REGION HAS BEEN AUTOMATICALLY GENERATED BY OROCHI SUMMONER.
///// Manual modification of this region is not recommended.
/////

_LIBRARY_FIND( rtcLib, hiprtcAddNameExpression );
_LIBRARY_FIND( rtcLib, hiprtcCompileProgram );
_LIBRARY_FIND( rtcLib, hiprtcCreateProgram );
_LIBRARY_FIND( rtcLib, hiprtcDestroyProgram );
_LIBRARY_FIND( rtcLib, hiprtcGetBitcode );
_LIBRARY_FIND( rtcLib, hiprtcGetBitcodeSize );
_LIBRARY_FIND( rtcLib, hiprtcGetCode );
_LIBRARY_FIND( rtcLib, hiprtcGetCodeSize );
_LIBRARY_FIND( rtcLib, hiprtcGetErrorString );
_LIBRARY_FIND( rtcLib, hiprtcGetLoweredName );
_LIBRARY_FIND( rtcLib, hiprtcGetProgramLog );
_LIBRARY_FIND( rtcLib, hiprtcGetProgramLogSize );
_LIBRARY_FIND( rtcLib, hiprtcLinkAddData );
_LIBRARY_FIND( rtcLib, hiprtcLinkAddFile );
_LIBRARY_FIND( rtcLib, hiprtcLinkComplete );
_LIBRARY_FIND( rtcLib, hiprtcLinkCreate );
_LIBRARY_FIND( rtcLib, hiprtcLinkDestroy );
_LIBRARY_FIND( rtcLib, hiprtcVersion );


///// END REGION: OROCHI_SUMMONER_REGION_hipew_cpp_rtc
///// (region automatically generated by Orochi Summoner)
#pragma endregion


	s_resultRtc = HIPEW_SUCCESS;
	*resultRtc = s_resultRtc;
  }
  else
  {
	s_resultRtc = HIPEW_ERROR_OPEN_FAILED;
	*resultRtc = s_resultRtc;
  }
}

const char *hipewErrorString(hipError_t result) {
  switch (result) {
    case hipSuccess: return "No errors";
    case hipErrorInvalidValue: return "Invalid value";
    case hipErrorOutOfMemory: return "Out of memory";
    case hipErrorNotInitialized: return "Driver not initialized";
    case hipErrorDeinitialized: return "Driver deinitialized";
    case hipErrorProfilerDisabled: return "Profiler disabled";
    case hipErrorProfilerNotInitialized: return "Profiler not initialized";
    case hipErrorProfilerAlreadyStarted: return "Profiler already started";
    case hipErrorProfilerAlreadyStopped: return "Profiler already stopped";
    case hipErrorNoDevice: return "No HIP-capable device available";
    case hipErrorInvalidDevice: return "Invalid device";
    case hipErrorInvalidImage: return "Invalid kernel image";
    case hipErrorInvalidContext: return "Invalid context";
    case hipErrorContextAlreadyCurrent: return "Context already current";
    case hipErrorMapFailed: return "Map failed";
    case hipErrorUnmapFailed: return "Unmap failed";
    case hipErrorArrayIsMapped: return "Array is mapped";
    case hipErrorAlreadyMapped: return "Already mapped";
    case hipErrorNoBinaryForGpu: return "No binary for GPU";
    case hipErrorAlreadyAcquired: return "Already acquired";
    case hipErrorNotMapped: return "Not mapped";
    case hipErrorNotMappedAsArray: return "Mapped resource not available for access as an array";
    case hipErrorNotMappedAsPointer: return "Mapped resource not available for access as a pointer";
    case hipErrorECCNotCorrectable: return "Uncorrectable ECC error detected";
    case hipErrorUnsupportedLimit: return "hipLimit_t not supported by device";
    case hipErrorContextAlreadyInUse: return "Context already in use";
    case hipErrorPeerAccessUnsupported: return "Peer access unsupported";
    case hipErrorInvalidKernelFile: return "Invalid ptx";
    case hipErrorInvalidGraphicsContext: return "Invalid graphics context";
    case hipErrorInvalidSource: return "Invalid source";
    case hipErrorFileNotFound: return "File not found";
    case hipErrorSharedObjectSymbolNotFound: return "Link to a shared object failed to resolve";
    case hipErrorSharedObjectInitFailed: return "Shared object initialization failed";
    case hipErrorOperatingSystem: return "Operating system";
    case hipErrorInvalidHandle: return "Invalid handle";
    case hipErrorNotFound: return "Not found";
    case hipErrorNotReady: return "HIP not ready";
    case hipErrorIllegalAddress: return "Illegal address";
    case hipErrorLaunchOutOfResources: return "Launch exceeded resources";
    case hipErrorLaunchTimeOut: return "Launch exceeded timeout";
    case hipErrorPeerAccessAlreadyEnabled: return "Peer access already enabled";
    case hipErrorPeerAccessNotEnabled: return "Peer access not enabled";
    case hipErrorSetOnActiveProcess: return "Primary context active";
    case hipErrorAssert: return "Assert";
    case hipErrorHostMemoryAlreadyRegistered: return "Host memory already registered";
    case hipErrorHostMemoryNotRegistered: return "Host memory not registered";
    case hipErrorLaunchFailure: return "Launch failed";
    case hipErrorCooperativeLaunchTooLarge: return "Cooperative launch too large";
    case hipErrorNotSupported: return "Not supported";
    case hipErrorUnknown: return "Unknown error";
    default: return "Unknown HIP error value";
  }
}

static void path_join(const char *path1,
                      const char *path2,
                      int maxlen,
                      char *result) {
#if defined(WIN32) || defined(_WIN32)
  const char separator = '\\';
#else
  const char separator = '/';
#endif
  int n = snprintf(result, maxlen, "%s%c%s", path1, separator, path2);
  if (n != -1 && n < maxlen) {
    result[n] = '\0';
  }
  else {
    result[maxlen - 1] = '\0';
  }
}

static int path_exists(const char *path) {
  struct stat st;
  if (stat(path, &st)) {
    return 0;
  }
  return 1;
}

const char *hipewCompilerPath(void) {
    #ifdef _WIN32
    const char *hipPath = getenv("HIP_ROCCLR_HOME");
    const char *windowsCommand = "perl ";
    const char *executable = "bin/hipcc";

    static char hipcc[65536];
    static char finalCommand[65536];
    if(hipPath) {
      path_join(hipPath, executable, sizeof(hipcc), hipcc);
      if(path_exists(hipcc)) {
        snprintf(finalCommand, sizeof(hipcc), "%s %s", windowsCommand, hipcc);
        return finalCommand;
      } else {
        printf("Could not find hipcc. Make sure HIP_ROCCLR_HOME points to the directory holding /bin/hipcc");
      }
    }
    #else
    const char *hipPath =  "opt/rocm/hip/bin";
    const char *executable = "hipcc";

    static char hipcc[65536];
    if(hipPath) {
      path_join(hipPath, executable, sizeof(hipcc), hipcc);
      if(path_exists(hipcc)){
        return hipcc;
      }
    }
    #endif

  {
#ifdef _WIN32
    FILE *handle = popen("where hipcc", "r");
#else
    FILE *handle = popen("which hipcc", "r");
#endif
    if (handle) {
      char buffer[4096] = {0};
      size_t elementSize = 1;
      size_t elementCount = sizeof(buffer) - 1;
      size_t len = fread(buffer, elementSize, elementCount, handle);
      buffer[len] = '\0';
      pclose(handle);
      if (buffer[0]) {
        return "hipcc";
      }
    }
  }

  return NULL;
}

int hipewCompilerVersion(void) {
  const char *path = hipewCompilerPath();
  const char *marker = "Hip compilation tools, release ";
  FILE *pipe;
  char buf[128];
  char output[65536] = "\0";
  char command[65536] = "\0";

  if (path == NULL) {
    return 0;
  }

  /* get --version output */
  strcat(command, "\"");
  strncat(command, path, sizeof(command) - 1);
  strncat(command, "\" --version", sizeof(command) - strlen(path) - 1);
  pipe = popen(command, "r");
  if (!pipe) {
    fprintf(stderr, "HIP: failed to run compiler to retrieve version");
    return 0;
  }

  while (!feof(pipe)) {
    if (fgets(buf, sizeof(buf), pipe) != NULL) {
      strncat(output, buf, sizeof(output) - strlen(output) - 1);
    }
  }

  pclose(pipe);
  return 40;
}
