



#
# In order to have Orochi compiled with CUDA, you need to define OROCHI_ENABLE_CUEW, and add the CUDA include path to your Orochi project.
#
# If your project is using cmake, this script can be included:
# it helps to configure your Orochi project
# for example, with a line looking like that:
#   include(${CMAKE_SOURCE_DIR}/contrib/Orochi/Orochi/enable_cuew.cmake)
#
#


cmake_minimum_required(VERSION 3.10)


# Function to join paths
function(join_paths result basePath additionalPath)
	if(WIN32)
		set(pathSeparator "\\")
	else()
		set(pathSeparator "/")
	endif()

	string(REGEX REPLACE "[/\\]+$" "" basePath "${basePath}")
	set(joinedPath "${basePath}${pathSeparator}${additionalPath}")
	set(${result} "${joinedPath}" PARENT_SCOPE)
endfunction()

# Function to check if a path is valid
function(path_ok result inPath)
	if(EXISTS "${inPath}" AND IS_DIRECTORY "${inPath}")
		set(${result} TRUE PARENT_SCOPE)
	else()
		set(${result} FALSE PARENT_SCOPE)
	endif()
endfunction()

# Region generated by Orochi Summoner
#REGION_PREMAKE_START CudaPath

# supported CUDA SDK majors, in order of preference. Any minor of these majors is accepted:
# the install directories are globbed, so a new 13.x or 12.x release is picked up without editing this list.
set(SUPPORTED_CUDA_MAJORS 13 12)
set(CUDA_INSTALL_ROOTS "/usr/local/cuda-" "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v")
set(BACKUP_CUDA_ENVVAR "CUDA_PATH")
set(BACKUP_CUDA_PATH_LINUX "/usr/local/cuda")

# REGION_PREMAKE_END

# this file is include()d into the caller's scope, so start from a known state rather than inheriting
# whatever the including project may have left in cuda_path.
set(cuda_path "")

# First, try the supported CUDA majors, in order of preference.
# Every assignment below is validated, so cuda_path is always either empty or an existing directory.
foreach(cuda_major IN LISTS SUPPORTED_CUDA_MAJORS)
	# an envvar set by the installer wins, so a SDK outside the standard folders is still found
	if(NOT cuda_path AND DEFINED ENV{CUDA_PATH_V${cuda_major}_0})
		path_ok(cuda_path_ok "$ENV{CUDA_PATH_V${cuda_major}_0}")
		if(cuda_path_ok)
			set(cuda_path "$ENV{CUDA_PATH_V${cuda_major}_0}")
		endif()
	endif()

	# otherwise look for any installed minor of this major and keep the highest one
	if(NOT cuda_path)
		set(best_minor -1)
		foreach(cuda_root IN LISTS CUDA_INSTALL_ROOTS)
			file(GLOB cuda_candidates "${cuda_root}${cuda_major}.*")
			foreach(cuda_candidate IN LISTS cuda_candidates)
				if(IS_DIRECTORY "${cuda_candidate}" AND cuda_candidate MATCHES "\\.([0-9]+)$")
					if(CMAKE_MATCH_1 GREATER best_minor)
						set(best_minor ${CMAKE_MATCH_1})
						set(cuda_path "${cuda_candidate}")
					endif()
				endif()
			endforeach()
		endforeach()
	endif()
endforeach()

if(NOT cuda_path)
	string(REPLACE ";" ".x or " supported_cuda_majors_pretty "${SUPPORTED_CUDA_MAJORS}")
	message(WARNING "No supported version of CUDA for this Orochi is found: needs a ${supported_cuda_majors_pretty}.x SDK. It's advised that you install one of these versions.")
endif()

# If CUDA still not found, search the "backup" paths
if(NOT cuda_path)
	if(DEFINED ENV{${BACKUP_CUDA_ENVVAR}})
		path_ok(cuda_path_ok "$ENV{${BACKUP_CUDA_ENVVAR}}")
		if(cuda_path_ok)
			set(cuda_path "$ENV{${BACKUP_CUDA_ENVVAR}}")
		endif()
	endif()
endif()

if(NOT cuda_path)
	path_ok(cuda_path_ok ${BACKUP_CUDA_PATH_LINUX})
	if(cuda_path_ok)
		set(cuda_path ${BACKUP_CUDA_PATH_LINUX})
	endif()
endif()

# Enable CUEW if CUDA is forced or if we find the CUDA SDK folder
option(FORCE_CUDA "Force enable CUDA" OFF)
if(FORCE_CUDA OR cuda_path)
	message(STATUS "CUEW is enabled.")
	add_definitions(-DOROCHI_ENABLE_CUEW)
endif()


# If we find the CUDA SDK folder, add it to the include dir
if(cuda_path)
	message(STATUS "CUDA SDK install folder found: ${cuda_path}")
	join_paths(cuda_include_path ${cuda_path} "include")
	include_directories(${cuda_include_path})
else()
	if(FORCE_CUDA)
		message(WARNING "WARNING: CUEW is enabled but it may not compile because CUDA SDK folder (CUDA_PATH) not found. You should install the CUDA SDK, or set CUDA_PATH.")
	else()
		message(WARNING "WARNING: CUEW is automatically disabled because CUDA SDK folder (CUDA_PATH) not found. You can force CUEW with the --forceCuda argument.")
	endif()
endif()
