

--
-- In order to have Orochi compiled with CUDA, you need to define OROCHI_ENABLE_CUEW, and add the CUDA include path to your Orochi project.
--
-- If your project is using premake, this script can be included:
-- it helps to configure your Orochi project
--
--
--


function oropremake_joinPaths(basePath, additionalPath)
	-- Detect the path separator based on the operating system
	local pathSeparator = package.config:sub(1,1)
	-- Check if the basePath already ends with a path separator
	if basePath:sub(-1) ~= pathSeparator then
		basePath = basePath .. pathSeparator
	end
	return basePath .. additionalPath
end

function oropremake_PathOK(inPath)
	if ( inPath == nil or inPath == '' ) then
		return false
	end
	if ( os.isdir(inPath) ) then
		return true
	end
	return false
end




-- REGION GENERATED BY OROCHI SUMMONER
--REGION_PREMAKE_START CudaPath

-- supported CUDA SDK majors, in order of preference. Any minor of these majors is accepted:
-- the install directories are globbed, so a new 13.x or 12.x release is picked up without editing this list.
supported_cuda_majors = { 13, 12 }
cuda_install_roots = { "/usr/local/cuda-", "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v" }
backup_cuda_envvar = "CUDA_PATH"
backup_cuda_path_linux = "/usr/local/cuda"

--REGION_PREMAKE_END



--
-- first, try the best CUDA paths ( the one that matches the version use for this Orochi )
--

cuda_path = nil

for _, cuda_major in ipairs(supported_cuda_majors) do
	if (not oropremake_PathOK(cuda_path)) then
		-- an envvar set by the installer wins, so a SDK outside the standard folders is still found
		cuda_path = os.getenv("CUDA_PATH_V" .. cuda_major .. "_0")
	end

	-- otherwise look for any installed minor of this major and keep the highest one
	if (not oropremake_PathOK(cuda_path)) then
		local best_minor = -1
		for _, cuda_root in ipairs(cuda_install_roots) do
			for _, cuda_dir in ipairs(os.matchdirs(cuda_root .. cuda_major .. ".*")) do
				local minor = tonumber(cuda_dir:match("%.(%d+)$"))
				if (minor ~= nil and minor > best_minor) then
					best_minor = minor
					cuda_path = cuda_dir
				end
			end
		end
	end
end

--
-- If CUDA still not found, search the "backup" paths
--

if (not oropremake_PathOK(cuda_path)) then
	cuda_path = os.getenv(backup_cuda_envvar)
end

-- if the CUDA PATH is not in the env var, search in the classic folder
if (not oropremake_PathOK(cuda_path)) then
	if ( os.isdir(backup_cuda_path_linux) ) then
		cuda_path = backup_cuda_path_linux
	end
end

-- warn only once the backup paths have been tried too, otherwise a SDK found through CUDA_PATH
-- or the default symlink would still be preceded by a "not found" message
if (not oropremake_PathOK(cuda_path)) then
	print("No supported version of CUDA for this Orochi is found: needs a " .. table.concat(supported_cuda_majors, ".x or ") .. ".x SDK. It's advised that you install one of these versions.")
end

-- Enable CUEW if CUDA is forced or if we find the CUDA SDK folder
if ( _OPTIONS["forceCuda"] or   oropremake_PathOK(cuda_path)  ) then
	print("CUEW is enabled.")
	defines {"OROCHI_ENABLE_CUEW"}
end

-- If we find the CUDA SDK folder, add it to the include dir
if (not oropremake_PathOK(cuda_path)) then
	if _OPTIONS["forceCuda"] then
		print("WARNING: CUEW is enabled but it may not compile because CUDA SDK folder ( CUDA_PATH ) not found. You should install the CUDA SDK, or set CUDA_PATH.")
	else
		print("WARNING: CUEW is automatically disabled because CUDA SDK folder ( CUDA_PATH ) not found. You can force CUEW with the --forceCuda argument.")
	end
else
	print("CUDA SDK install folder found: " .. cuda_path)
	includedirs {  oropremake_joinPaths(cuda_path,"include") }
end


