



#
# In order to have Orochi compiled with CUDA, you need to define OROCHI_ENABLE_CUEW, and add the CUDA include path to your Orochi project.
#
# If your project is using cmake, this script can be included:
# it helps to configure your Orochi project
# for example, with a line looking like that:
#   include(${CMAKE_SOURCE_DIR}/contrib/Orochi/Orochi/enable_cuew.cmake)
#
#


cmake_minimum_required(VERSION 3.10)


# Function to join paths
function(join_paths result basePath additionalPath)
	if(WIN32)
		set(pathSeparator "\\")
	else()
		set(pathSeparator "/")
	endif()

	string(REGEX REPLACE "[/\\]+$" "" basePath "${basePath}")
	set(joinedPath "${basePath}${pathSeparator}${additionalPath}")
	set(${result} "${joinedPath}" PARENT_SCOPE)
endfunction()

# Function to check if a path is valid
function(path_ok result inPath)
	if(EXISTS "${inPath}" AND IS_DIRECTORY "${inPath}")
		set(${result} TRUE PARENT_SCOPE)
	else()
		set(${result} FALSE PARENT_SCOPE)
	endif()
endfunction()

# Region generated by Orochi Summoner
#REGION_PREMAKE_START CudaPath

# supported CUDA SDKs, in order of preference: the first one found is used
set(SUPPORTED_CUDA_VERSION_NAMES "13.0" "12.2")
set(SUPPORTED_CUDA_ENVVARS "CUDA_PATH_V13_0" "CUDA_PATH_V12_2")
set(SUPPORTED_CUDA_PATHS_LINUX "/usr/local/cuda-13.0" "/usr/local/cuda-12.2")
set(SUPPORTED_CUDA_PATHS_WINDOWS "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v13.0" "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2")
set(BACKUP_CUDA_ENVVAR "CUDA_PATH")
set(BACKUP_CUDA_PATH_LINUX "/usr/local/cuda")

# REGION_PREMAKE_END

# First, try the supported CUDA paths, in order of preference
list(LENGTH SUPPORTED_CUDA_VERSION_NAMES supported_cuda_count)
math(EXPR supported_cuda_last "${supported_cuda_count} - 1")

foreach(cuda_index RANGE ${supported_cuda_last})
	list(GET SUPPORTED_CUDA_ENVVARS ${cuda_index} cuda_envvar)
	list(GET SUPPORTED_CUDA_PATHS_LINUX ${cuda_index} cuda_path_linux)
	list(GET SUPPORTED_CUDA_PATHS_WINDOWS ${cuda_index} cuda_path_windows)

	# try the envvar
	if(NOT cuda_path AND DEFINED ENV{${cuda_envvar}})
		set(cuda_path $ENV{${cuda_envvar}})
	endif()

	# if not found in envvar, try if path exist ( linux )
	if(NOT cuda_path)
		path_ok(cuda_path_ok ${cuda_path_linux})
		if(cuda_path_ok)
			set(cuda_path ${cuda_path_linux})
		endif()
	endif()

	# try the windows path
	if(NOT cuda_path)
		path_ok(cuda_path_ok "${cuda_path_windows}")
		if(cuda_path_ok)
			set(cuda_path "${cuda_path_windows}")
		endif()
	endif()
endforeach()

if(NOT cuda_path)
	string(REPLACE ";" " or " supported_cuda_names_pretty "${SUPPORTED_CUDA_VERSION_NAMES}")
	message(WARNING "No supported version of CUDA for this Orochi is found: ${supported_cuda_names_pretty}. It's advised that you install one of these versions.")
endif()

# If CUDA still not found, search the "backup" paths
if(NOT cuda_path)
	if(DEFINED ENV{${BACKUP_CUDA_ENVVAR}})
		set(cuda_path $ENV{${BACKUP_CUDA_ENVVAR}})
	endif()
endif()

if(NOT cuda_path)
	path_ok(cuda_path_ok ${BACKUP_CUDA_PATH_LINUX})
	if(cuda_path_ok)
		set(cuda_path ${BACKUP_CUDA_PATH_LINUX})
	endif()
endif()

# Enable CUEW if CUDA is forced or if we find the CUDA SDK folder
option(FORCE_CUDA "Force enable CUDA" OFF)
if(FORCE_CUDA OR cuda_path)
	message(STATUS "CUEW is enabled.")
	add_definitions(-DOROCHI_ENABLE_CUEW)
endif()


# If we find the CUDA SDK folder, add it to the include dir
if(cuda_path)
	message(STATUS "CUDA SDK install folder found: ${cuda_path}")
	join_paths(cuda_include_path ${cuda_path} "include")
	include_directories(${cuda_include_path})
else()
	if(FORCE_CUDA)
		message(WARNING "WARNING: CUEW is enabled but it may not compile because CUDA SDK folder (CUDA_PATH) not found. You should install the CUDA SDK, or set CUDA_PATH.")
	else()
		message(WARNING "WARNING: CUEW is automatically disabled because CUDA SDK folder (CUDA_PATH) not found. You can force CUEW with the --forceCuda argument.")
	endif()
endif()
