#version 460 core
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_scalar_block_layout : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_EXT_buffer_reference2 : require

layout(set = 0, binding = 0, scalar) buffer Data { float data[]; };

layout(local_size_x = 8) in;

void main() { data[gl_GlobalInvocationID.x] = float(gl_GlobalInvocationID.x); }